import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen bg-gradient-to-tr from-orange-400 to-pink-600 flex justify-center items-center">
        <h1 className="text-white text-5xl">Hello World</h1>
      </main>
    </>
  );
}
